### Learning pandas 2

In [3]:
import pandas as pd
import numpy as np

In [13]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
# print df2
df2

# view the head and tail of the data:
print(df2.head(2))
df2.tail(3)



     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo


A          B    C  D      E    F
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [26]:
# create a dataframe by passing a numpy array with a datetime index using date_range() and labeled columns:

dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)


# print out the cols and indexes:
# print(df.index)
print(df.index)
print(df.columns)
# 

# return the numpy representation of the dataframe:
print("\n The numpy representation of the dataFrame is : \n",df.to_numpy())


                   A         B         C         D
2013-01-01 -0.185720  0.717981 -1.451805 -0.033023
2013-01-02  1.275307 -0.960215  0.093474 -0.423651
2013-01-03 -0.279742 -1.058214  1.602458 -0.416216
2013-01-04 -0.595077 -1.730041 -0.174761  0.691903
2013-01-05  0.493486  0.532965  1.506266  0.968924
2013-01-06 -0.269425 -1.223668 -0.809131  0.089838
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

 The numpy representation of the dataFrame is : 
 [[-0.18571969  0.71798098 -1.45180545 -0.03302345]
 [ 1.27530706 -0.96021526  0.09347431 -0.42365146]
 [-0.27974166 -1.05821426  1.60245765 -0.41621597]
 [-0.59507664 -1.73004054 -0.17476128  0.69190265]
 [ 0.49348614  0.53296524  1.50626626  0.96892418]
 [-0.26942463 -1.22366757 -0.80913071  0.08983772]]


In [33]:
# Use describe to show the statistical information of my data:
print(df.describe())

print("\n \n The transposed Matrix is: ")

# Transposed the data and got the description of the dataFrame
transposedData = df.T
print(transposedData.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.073138 -0.620199  0.127750  0.146296
std    0.689535  1.002388  1.228047  0.574631
min   -0.595077 -1.730041 -1.451805 -0.423651
25%   -0.277162 -1.182304 -0.650538 -0.320418
50%   -0.227572 -1.009215 -0.040643  0.028407
75%    0.323685  0.159670  1.153068  0.541386
max    1.275307  0.717981  1.602458  0.968924

 
 The transposed Matrix is: 
       2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
count    4.000000    4.000000    4.000000    4.000000    4.000000    4.000000
mean    -0.238142   -0.003771   -0.037929   -0.451994    0.875410   -0.553096
std      0.900365    0.955089    1.145051    1.006518    0.472532    0.579958
min     -1.451805   -0.960215   -1.058214   -1.730041    0.493486   -1.223668
25%     -0.502241   -0.557792   -0.576716   -0.878818    0.523095   -0.912765
50%     -0.109372   -0.165089   -0.347979   -0.384919    0.750945   -0.539278
75%      

In [36]:
# sorting:
# Axis can either be 0 or 1, 0 being default, fliped to 1, the A goes to the end:
df.sort_index(axis=0, ascending=True)

A         B         C         D
2013-01-01 -0.185720  0.717981 -1.451805 -0.033023
2013-01-02  1.275307 -0.960215  0.093474 -0.423651
2013-01-03 -0.279742 -1.058214  1.602458 -0.416216
2013-01-04 -0.595077 -1.730041 -0.174761  0.691903
2013-01-05  0.493486  0.532965  1.506266  0.968924
2013-01-06 -0.269425 -1.223668 -0.809131  0.089838