### Install neccessary dependencies:

In [6]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


### Basics of numpy:

In [18]:
import numpy as np

# creating an array:
arr1 = np.array([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]])
print(arr1)

# get number fo dimentions:
print("Number of dimentions: ", arr1.ndim)

# get th saspe of matrix:
print("Shape of the matrix is : ",arr1.shape)

# size of matrix:
print("Size of matrix is : ", arr1.size)

# data type of elems in matrix:
print("Data type of elems in matrix: ", arr1.dtype.name)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Number of dimentions:  2
Shape of the matrix is :  (3, 4)
Size of matrix is :  12
Data type of elems in matrix:  int64


### Mathematical operations:

In [24]:

a = np.array([11,12,13,14])
b = np.array([1,2,3,4])
c = a-b

# print the c array and square every elem:
print(c)
print(c**2)

# conditional operations:
print(b > 2)




[10 10 10 10]
[100 100 100 100]
[False False  True  True]


In [31]:
# marix multiplication:
A1 = np.array([
    [1,1],
    [0,1]
])
A2 = np.array([
    [2,0],
    [3,4]
])
print(A1 * A2) # multiply the matrices

# indexing:
arr1 = np.array([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]])

print("index grabbed: ", arr1[0,1])
print("index grabbed first row, first elem to third", arr1[0, 0:3])
print("index grabbed first row, all elems in it", arr1[0, :])




[[2 0]
 [0 4]]
index grabbed:  1
index grabbed first row, first elem to third [0 1 2]
index grabbed first row, all elems in it [0 1 2 3]


### Shape manipulation:

In [41]:
arr1 = np.array([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]])
print(arr1.ravel())

arr1.shape = (6,2)
print("The shape has been changed to 6x2 \n", arr1)

# arr1.transpose()
print("The transposed matrix is : \n", arr1.transpose()) # passed by value, not reference
# print(arr1)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
The shape has been changed to 6x2 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
The transposed matrix is : 
 [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
